# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.

{
    'name': 'All in one Receipt Reports - Sales, Purchase, Accounting, Inventory',
    'version': '19.0.1.0',
    'category': 'Sales,Purchases,Accounting,Warehouse',
    'author': 'OMAX Informatics',
    'website': 'www.omaxinformatics.com',
    'description' : '''
       This module helps to print Receipt Reports for Sales, Purchase, Accounting and Inventory.
    ''',
    'depends': ['sale','sale_management','account','stock','purchase','web'],
    'data': [
        'report/report_view.xml',
        'report/receipt_sale_order_template.xml',
        'report/receipt_purchase_order_template.xml',
        'report/receipt_rfq_template.xml',
        'report/receipt_picking_operation_template.xml',
        'report/receipt_delivery_slip_template.xml',
        'report/receipt_invoice_template.xml',
        'report/receipt_invoice_wp_template.xml',
        'report/receipt_payment_slip_template.xml',
    ],
    'demo': [],
    'test': [],
    'images': ['static/description/banner.png'],
    'license': 'OPL-1',
    'currency':'USD',
    'price': 30.0,
    'installable' : True,
    'auto_install' : False,
    'application' : True,
    'pre_init_hook': 'pre_init_check',
    'module_type': 'official',
    'summary': '''
    	All in one Receipt Reports - Sales, Purchase, Accounting, Inventory,
    	Sales Receipt Report,
    	Purchase Receipt Report,
    	Quotation Receipt Report,
    	Invoice Receipt Report,
    	Bill Receipt Report,
    	Sale Order Receipt Report,
    	Purchase Order Receipt Report,
    	Inventory Receipt Report,
    	Delivery Order Receipt,
    	RFQ Receipt Report,
    	Request For Quotation Receipt,
    	Accounting Receipt Report,
    	Slip Reports,
    	Sale Slip,
    	Sales Slip,
    	Purchase Slip,
    	Account Slip,
    	Stock Slip,
    	Invenotry Slip,
    	Payment Receipt Report,
    	Customer Payment Receipt Report,
    	Vendor Payment Receipt Report,
    ''',
}

